- name: add secondary IP to the interface
  nmcli:
    conn_name: "System eth0"
    type: ethernet
    ip4: 192.168.121.8
    gw4: 192.168.121.1
    state: present
    autoconnect: yes

- name: set new dns server to the secondary network interface
  nmcli:
    conn_name: "System eth1"
    type: ethernet
    dns4:
    - 1.1.1.1
    state: present

- name: refresh interface eth0
  command: nmcli c up System\ eth0
  register: nmcli_refresh

- name: show refresh output
  debug:
    var: nmcli_refresh
