- name: install nginx
  yum:
    name:
      - nginx
    state: latest

- name: adding demo conf for nginx
  copy:
    src: ./files/nginx.conf
    dest: /etc/nginx/conf.d/demo.conf
    owner: root
    group: root

- name: ensure nginx folder belongs to nginx user
  file:
    path: "/nginx"
    state: directory
    owner: nginx
    group: nginx
    remote_src: yes

- name: make sure nginx is started
  systemd:
    name: nginx
    state: started
    enabled: yes